### ISSUE TITLE
How to have "halt" be the last command in runlevel 0?

### ISSUE THREAD

**Issue by pierre-labastie** [lfs-book/LSB-Tools#11]
I've added a script in /etc/rc.d/init.d which shuts down the UPS in case of power failure. I've manually created a link in rc0.d:
```
S98ups-shutdown -> ../init.d/ups-shutdown
```
and since I have
```
S99halt -> ../init.d/halt
```
the UPS is shut down (if /etc/powerfail exists) before halting the computer.

Problem is that, when running install_initd (for installing another script), I get (output from `--dryrun`):
```
[...]
Removing /etc/rc.d/rc0.d/S99halt
Removing /etc/rc.d/rc0.d/S98ups-shutdown
Adding /etc/rc.d/rc0.d/S00halt -> ../init.d/halt
Adding /etc/rc.d/rc0.d/S50ups-shutdown -> ../init.d/ups-shutdown
[...]
```
so that the order is wrong.

I have tried to add `$last` in the halt script `Required-Start:` or `Should-Start:` lines, and it does not change the result. FWIIW, here is the LSB header for ups-shutdown:
```
### BEGIN INIT INFO
# Provides:            ups-shutdown
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       0
# Default-Stop:
# Short-Description:   Shut down the UPS in case of detected power failure
# Description:         Shut down the UPS in case of detected power failure
# X-LFS-Provided-By:
### END INIT INFO
```
Note that the `rc` script in the lfs bootscripts runs `<scriptname> stop` for a script starting with `S` in runlevel 0. But it runs `S` scripts after the `K` ones, so this is what we want.

I've tried to put `Required-Start: ups-shutdown` in the `halt` script (although I think the halt script shouldn't be dependent on whatever comes before it), and I still get the above ordering... Not sure whether I am doing something wrong...

**Comment by djlucas** [comment]
Add "halt" to required-stop for ups-shutdown. Required-stop means that the required service must not have been stopped prior to stopping the current script.

**Comment by pierre-labastie** [comment]
I've tried what you propose, still the same result...

Actually, those services are not "stopped" but "started" in runlevel 0: they have ```Default-Start:       0```, not ```Default-Stop:```, and in the lfs-bootscript Makefile, halt is symlinked to as S99halt in rc0.d (not Kxxx)
