### ISSUE TITLE
Switch away from setup.py

### ISSUE THREAD

**Issue by xry111** [lfs-book/LSB-Tools#13]
Directly running setup.py is deprecated and it produces some DeprecationWarning.  Unfortunately pip-based installation seems not possible because pip cannot create files in /usr/lib/lsb.

Maybe we can use pip-based installation and symlink the needed files to /usr/lib/lsb with explicit book instructions?  Or just use a plain Makefile to install the package?

**Comment by renodr** [comment]
I think the plain Makefile is going to be best here. We're only installing a handful of files so going through the pip-based installation process feels overcomplicated for what we need to do
